[package]
name = "multilinear-prover"
authors = ["Jules de Smit <jds@matterlabs.dev>"]
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
rand = "0.8.5"
rayon = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
